### ISSUE TITLE
Software Specific Section

### ISSUE THREAD

**Issue by thetechnocrat-dev** [DeSciWorldDAO/awesome-desci#23]
Hi all, this comprehensive curation of DeSci organizations and papers is great 💯 

Wondering what the team's thoughts are for adding a section of DeSci Software Repositories. This would help engineers use each other's libraries and projects.

Happy to make a PR with some initial projects if you all like this idea.

**Comment by gingerheart86** [comment]
Hey! 
Great idea.
Go ahead!

**Comment by thetechnocrat-dev** [comment]
Great! @gingerheart86, I added PR https://github.com/DeSciWorldDAO/awesome-desci/pull/24
