### ISSUE TITLE
KidneyDAO

### ISSUE THREAD

**Issue by tuanucsb** [DeSciWorldDAO/awesome-desci#32]
Hi,
It would be great if you can include KidneyDAO on your list. We focus exclusively on Kidney health. We just started out and recruiting members.  Our website is https://www.kidneydao.com/ and the discord is at https://discord.gg/BeeCnerPTv

Thanks so much!
Tuan

**Comment by gingerheart86** [comment]
Hey Tuan. 
You can edit the table of the orgs and PR.
Let me know!

Kind regards
Carolina
